### PR TITLE
Remove 8 11

### PR DESCRIPTION
**Pull request by Casteran**
Intent to remove Coq8.11 (because of Hint attributes)
references to Ackermann in the README

### CODE REVIEW

**Comment by palmskog** [comment]
@Casteran I see what you are trying to do, but I think unfortunately we can't use the templates generation script like this. The problem is that hydra-battles has too much customization compared to the average Coq project, which we optimize the templates for. I'm going to synchronize with @Zimmi48 exactly how we should set up template-based generation. Maybe it should be a custom script hosted in the project.

**Comment by palmskog** [comment]
@Casteran unless you have objections, I will do a quick refactoring later tonight of the changes in this branch, while preserving the content. I think the project should keep using a custom README (rather than the generated one currently in the PR) for the time being.

**Comment by Casteran** [comment]
No abjections at all.
Apart from the 8.11 issue, I made small changes in the meta.yml file :
  Add a phrase about the Ackermann sub-directory
  Add primitive-recursive-functions and Peano-arithmetics as keywords
  Add Russel in the actors field

 Is it possible to report these changes in master (before deleting remove-8-11) ?
Thanks !

**Comment by palmskog** [comment]
Yes, I will make sure these changes will survive the merge to the master branch.

**Pull request closed without merging**
