### PR TITLE
Add Alectryon section and dix some TODOs

### PR DESCRIPTION
**Pull request by cpitclaudel**

### CODE REVIEW

**Comment by Casteran** [comment]
Hi !
@cpitclaudel  I tried the new makefile, but I get errors "File `snippets/Hprime/HprimeDef.tex' not found".
Do I have to copy manually useful snippets from doc/movies to doc/JFLA2022 (as before) or is there a Make entry do do that ?

**Comment by Casteran** [comment]
Doing "make" in JFLA2022 directory seems to remove the contents of ./snippets/XXX/  and results in "not found" errors.
I could get a pdf version of pdf by  a) copying several snippets from doc/movies/snippets/XXX to doc/JFLA2022/snippets/XXX  b) compiling manually (through a sequence of pdflatex and bibtex).  Any call to "make" resulted in the issue above.  Sure I didn't understand the new Makefile ? 
Anyway, we are on 9 pages (bibliography included). 
@cpitclaudel : Including a snippet with a comutation is a good idea.

**Comment by Casteran** [comment]
Here is the sequence of comands I sent to look quickly at the current version (not a Makefile yet  !)

```
cp doc/movies/snippets/E0/Ex42.tex doc/JFLA2022/snippets/E0
cp doc/movies/snippets/Hprime/HprimeDef*.tex doc/JFLA2022/snippets/Hprime
cp doc/movies/snippets/Schutte/*.tex doc/JFLA2022/snippets/Schutte
cp doc/movies/snippets/Pow/evalPow17LetIn.tex doc/JFLA2022/snippets/Pow/


pdflatex paper; bibtex paper; pdflatex paper; pdflatex paper
```

**Comment by Casteran** [comment]
@cpitclaudel  The section about Alectryon looks very nice to me. Perhaps we would find a sentence or two explaining why a pure coqdoc-like pdf generation wouldn't work: the structure of the book (driven by the mathematical themes) is independent from the library's.
Your remark about ligatures : which font do you suggest ?

**Comment by Casteran** [comment]
There remains a small inconstency on the way we cite tools and libraries: ocurrences of "Coq" and "\emph{Coq}" , etc.
Which is the best one ?

**Comment by Zimmi48** [comment]
> There remains a small inconstency on the way we cite tools and libraries: ocurrences of "Coq" and "\emph{Coq}" , etc. Which is the best one ?

Similarly to what @palmskog suggested for the Hydras & co project itself, if we want a consistent style, we should probably define a macro and use it.

**Comment by cpitclaudel** [comment]
> @cpitclaudel I tried the new makefile, but I get errors "File `snippets/Hprime/HprimeDef.tex' not found".

Sorry about that!  Let me have a look.

**Comment by Casteran** [comment]
@cpitclaudel  I changed the EX42e snippet (in ordinals/Schutte/Schutte.v): I added a no-hyps, which makes the result nicer.

**Comment by Casteran** [comment]
> > There remains a small inconstency on the way we cite tools and libraries: ocurrences of "Coq" and "\emph{Coq}" , etc. Which is the best one ?
> 
> Similarly to what @palmskog suggested for the Hydras & co project itself, if we want a consistent style, we should probably define a macro and use it.

OK, I'll do that !

**Pull request merged**
