### PR TITLE
Improvements to the README.

### PR DESCRIPTION
**Pull request by Zimmi48**
Here are a few suggestions to improve the README:

- I have added the standard coq-community badges, except that the "contributions | welcome" badge points to the "Contributions are welcome!" section of the README instead of pointing to the generic https://github.com/coq-community/manifesto/blob/master/CONTRIBUTING.md.

- I have changed the documentation on dependencies to explain how to get them through opam, and how to only get the ones you need for a specific part, and I have added instructions to build only a specific part thanks to Dune.

- I have fixed a markdown problem in the description of the sources.

[Preview here](https://github.com/Zimmi48/hydra-battles/blob/readme-improvement-proposals/README.md).

What do you think? I can revert anything you don't like.

### CODE REVIEW

**Comment by Zimmi48** [comment]
PS: @Casteran unless you click on "Watch", you will not receive notifications for issues / pull requests where you are not mentioned / requested a review.

**Comment by Casteran** [comment]
Ok ! Thank you !

**Comment by Casteran** [comment]
Nice! Thank you!

**Review by Casteran — APPROVED** [review]
I approve these changes

**Pull request merged**
