### PR TITLE
Update Coq Nix Toolbox.

### PR DESCRIPTION
**Pull request by Zimmi48**
Let's see if this fixes the strange CI failure.

### CODE REVIEW

**Comment by Casteran** [comment]
The last error is mine, "omega_Small «  instead of « Omega_Small ». I didn’t notice it, because on MacOS this is more or less the same file name.
I pushed the correction on master.

**Comment by Casteran** [comment]
Apart from this error (in doc/part-hydras.tex) the CI failure looks to be fixed.

**Comment by Casteran** [comment]
It’s working ! Thanks !

**Comment by Zimmi48** [comment]
The issue was that the preview branch for the Coq Nix Toolbox had been force-pushed to: https://github.com/coq-community/coq-nix-toolbox/issues/61
Now that we are using the official `master` branch of the Coq Nix Toolbox instead, the problem shouldn't happen again.

**Pull request merged**
