### PR TITLE
Subtree-based Ackermann

### PR DESCRIPTION
**Pull request by palmskog**
Includes all changes from the `with-ackermann` branch, but includes the history of all the Ackermann files.

@Casteran let me know if this is OK to merge.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I thought that the plan was that the hydra-battles repository would now contain three opam packages (coq-ackermann, coq-hydra-battles and coq-addition-chains) instead of two. But if I understand correctly, what is implemented in the with-ackermann branch and in this PR is instead to merge the coq-ackermann and coq-hydra-battles packages together. This other strategy is also fine with me, but since this is not the same, I just want to make sure that it's a conscious design choice.

**Comment by palmskog** [comment]
@Zimmi48 yes, I had initially hoped to make three separate packages, but this is not possible due to how Pierre wants the files to cross-depend on each other. So I think this is the best solution for what he wants to do.

**Comment by Zimmi48** [comment]
OK, it makes total sense if the two parts are intertwined!

**Comment by Casteran** [comment]
@palmskog  Sounds good !  Do I just have to merge ?

**Pull request merged**
