### PR TITLE
[movies] Simplify the driver

### PR DESCRIPTION
**Pull request by cpitclaudel**
This is a follow-up to https://github.com/coq-community/hydra-battles/issues/70

With the change that I suggested there, I was able to refactor the movies script into a standard Alectryon pipeline, with just a few custom actions to isolate snippets in the source `.v` file.

@Casteran I tried to make a minimally invasive patch, so I didn't touch the source files.  Instead I just made the code look for existing `(*| .. coq:: …flags… |*)` annotations and propagate the corresponding flags.

I kept the folder structure, and AFAICT the only differences are spaces; I hope I didn't miss anything (I made it so that spaces before and after snippets get stripped (which is a bit tricky due to `(*| .. coq |*)` visibility annotations).

This pipeline doesn't go through reST at all.  `(*| .. coq |*)` visibility annotations outside of snippets are ignores.  Visibility settings get reset after each snippet, so `(*||*)` can be useful in the middle of a snippet but is not needed at the end of a snippet.

The syntax `(* begin snippet ABC:: …flags… *)` is supported but not used (to avoid a larger diff than necessary.

@Zimmi48 I need your help to pull the latest Alectryon.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I pushed the same commit as on top of #67 to test the latest `master` version of Alectryon.

**Comment by Casteran** [comment]
Looks nice !
Just a naive question : Do I have to update my (pip installed) version of alectryon on my machine ?

**Comment by Zimmi48** [comment]
Yes, to merge this PR and #67, there are two options:
1. wait for Clément to make a new release and require it instead of the current 1.3
2. run `pip install` from the GitHub repository of Alectryon (and document that this is required).

**Comment by Zimmi48** [comment]
Something I've just noticed is that ever since this PR, the "Build Alectryon snippets" step in the build-doc job does nothing and all the snippet building is actually done in the "Compile LaTeX document" step. I don't really understand why that would be the case given that the `Makefile` in `doc/movies` is still there.

**Comment by cpitclaudel** [comment]
> I don't really understand why that would be the case given that the Makefile in doc/movies is still there.

Thanks for catching that, fixed in https://github.com/coq-community/hydra-battles/pull/84

**Pull request merged**
