### PR TITLE
Add some snippets

### PR DESCRIPTION
**Pull request by Zimmi48**
I did some experiments locally. However, for some reason, I couldn't yet produce a PDF with the Coq answers, so I will use this PR to check if that's produced correctly.

### CODE REVIEW

**Comment by Casteran** [comment]
Which kind of Coq answer did cause problems ? Answers to simple requests as Print, About, etc. Or goal displaying ?



Envoyé de mon iPad

**Comment by Zimmi48** [comment]
Everything, but that's because my coq-serapi is not correctly installed. The problem doesn't show up in the version built by the CI.

**Comment by Casteran** [comment]
Ok, so it's safe to merge  this PR to master now ?

**Comment by Zimmi48** [comment]
The `Check` were printing output contrary to the previous version so I've pushed a new commit to try to mask the output. I'm waiting for the result of CI to see if that works.

**Comment by Zimmi48** [comment]
OK, it worked! So this is ready to merge.

**Comment by Casteran** [comment]
How about adding in the pdf doc and README.md a paragraph like:
" An increasing part of the hydras.pdf document is written with the help of the Alectryon software [...], replacing old
  copy-pasted quotations  with snippets  generated from the source and answers by the system.
    <descrition of the snippet tools, and credits>. "

**Comment by Zimmi48** [comment]
Good idea

**Pull request merged**
