### PR TITLE
[doc] Add an \inputsnippets command and demo it in Schutte/AP.v

### PR DESCRIPTION
**Pull request by cpitclaudel**
As discussed in https://github.com/coq-community/hydra-battles/issues/70 ; see the diff.
I'll need @Zimmi48 to fetch the latest Alectryon for this to work, though :innocent:

### CODE REVIEW

**Comment by cpitclaudel** [comment]
image

**Comment by Casteran** [comment]
Thanks! The demo is very nice!

**Comment by Zimmi48** [comment]
I've done the update. I've checked that the generated PDF does correspond to the screenshot.

**Comment by Casteran** [comment]
> I've done the update. I've checked that the generated PDF does correspond to the screenshot.

Thanks! I've tested inputsnippets on a local branch, which I will merge this afternoon. It helps a lot to write more readable `.v`and `pdf`!

**Pull request merged**
