### PR TITLE
depend on coq-gaia-schutte opam package and test in opam CI

### PR DESCRIPTION
**Pull request by palmskog**
Thanks to package definitions in the Coq opam repo, this should hopefully "just work".

### CODE REVIEW

**Comment by palmskog** [comment]
CI is apparently not triggering due to ongoing GitHub issues, I will force-push at some later point.

**Comment by Casteran** [comment]
@palmskog  Looks like there are issues with `rewrite ... in ...` in Coq 8.13.
Should I remove all occurrences of this pattern in `theories/gaia/`  (if it's bad SSR style) ?

**Comment by palmskog** [comment]
@Casteran indeed, `rewrite ... in ...` is not an idiom recommended in the SSReflect world (it indicates inadequate context management via `move`). However, rather than fixing this in the PR, maybe we can merge the PR? And you can fix it at some later point, or you can ask me to drop support for 8.13 in CI.

**Comment by Casteran** [comment]
> @Casteran indeed, `rewrite ... in ...` is not an idiom recommended in the SSReflect world (it indicates inadequate context management via `move`). However, rather than fixing this in the PR, maybe we can merge the PR? And you can fix it at some later point, or you can ask me to drop support for 8.13 in CI.

Well, I think it'd be better to respect SSReflect's idioms as much as possible.
So, you propose to merge into master, then I replace in priority the `rewrite ... in` which deal with setoids, then the others. For a few days, I will have 8.13 failures.
Right?

**Comment by palmskog** [comment]
@Casteran usually it's a good idea to have a green CI. I'm thinking we could just disable the Docker CI for 8.13 if you don't mind, then re-enable it once you fix the `rewriting .. in` (ping me in the pull request).

**Comment by Casteran** [comment]
@palmskog I just removed fifty occurrences of `rewrite ... in ...` in the Gaia-Bridge files. The result isn't pretty, but next weeks I will work on these files:
   - improve the use of `move` and derivates 
   - make some decidable predicates boolean functions (e.g. `path`)
When it looks better, we may make and advertise a `1.0` release ...

**Pull request merged**
