### PR TITLE
Update to Alectryon 1.3

### PR DESCRIPTION
**Pull request by cpitclaudel**
I've had a quick look at the output, and it seems reasonable to me; I hope I didn't break things.  Please check and let me know.
I also took the liberty to fix a typo in the README and to use the new LuaLaTeX backend in Alectryon.

The update was supposed to be transparent, but I missed two trivial breaking changes; hence the patch :/  On the plus side, hypotheses and goals should display significantly better now.

### CODE REVIEW

**Comment by Casteran** [comment]
> I've had a quick look at the output, and it seems reasonable to me; I hope I didn't break things. Please check and let me know.
> I also took the liberty to fix a typo in the README and to use the new LuaLaTeX backend in Alectryon.
> 
> The update was supposed to be transparent, but I missed two trivial breaking changes; hence the patch :/ On the plus side, hypotheses and goals should display significantly better now.

@cpitclaudel Thank you very much !!!
In order to check goal displays, I just commit a change (remove a .no-out in theories/ordinals/Epsilon0/T1.v, snippet LTOnea, which is displayed p80 of the pdf.  There is still a problem on my machine, but it may be a problem of local installation.

**Comment by Casteran** [comment]
@cpitclaudel  The same issue happens on CI.  
I will temporarily restore the (* .no-out *) (4th line of Lemma LT_one), for having a clean hydras.pdf on the coq-community site.
For testing the vertical alignment of subgoals, it is possible to remove it, then `touch doc/hydras.tex`

**Comment by cpitclaudel** [comment]
Thanks for testing.  I see the problem now; I had built from inside Emacs and it used xelatex instead of lualatex by default.  I will investigate.

**Comment by cpitclaudel** [comment]
OK, fixed in v1.3.1, thanks a lot.

image

By the way, if you prefer one hypothesis per line, you can use this:

```
\makeatletter
\renewcommand{\alectryon@hyps@sep}{\alectryon@nl}
\makeatother
```


image

**Comment by Casteran** [comment]
Great !!! Thanks a lot !!!

**Pull request merged**
