### PR TITLE
Restructuration

### PR DESCRIPTION
**Pull request by Casteran**
Proposition to merge restructuration into master.

### CODE REVIEW

**Comment by palmskog** [comment]
@Casteran to keep the namespacing simpler, how about:
- `theories/ordinals` is simply `hydras`
- `theories/additions` is simply `additions`

However, this would mean rolling back all the changes to the `From` statements, i.e., you should have `From hydras Require Import ...` instead of `From hydras.ordinals Require Import ...`.

**Comment by Casteran** [comment]
Yes, I can do that (in the .v files). With grep, it will be fast. I have to go outside for one hour, when I come back, I change the Requires, then the href in there latex file.
I send you  an email when I have finished.

**Comment by Casteran** [comment]
I made the changes in branch restructuration.
Files modified :  _CoqProject  theories/ordinals/*/*.v doc/part-hydras.tex 

I didn’t modify dune nor opam related files.

Would you check before merge ?
Many thanks.

**Comment by Casteran** [comment]
Oups, it works on my computer, but I just receive an error message from CI:
All jobs have failed (on branch restructuration) 
The error messages are 
Cannot find a physical path bound to logical path matching suffix

**Comment by palmskog** [comment]
@Casteran I fixed the last issue with the build, so I think this is ready for merging now.

However, note that `make install` will no longer be sensical - the right way to install (in contrast to working in the local directory) is instead via Dune, which the opam files will use.

**Pull request merged**
