### PR TITLE
remove a bunch of deprecate warnings

### PR DESCRIPTION
**Pull request by Casteran**

### CODE REVIEW

**Comment by Casteran** [comment]
The CI seems to check until 8.17.  On my Mac, 8.18 is OK.

**Comment by palmskog** [comment]
@Casteran you mean you want me to add CI for 8.18 into the PR here?

**Comment by Casteran** [comment]
Well, I mean,  only if you find it appropriate.  I  just wanted to know if my corrections are OK with 8.18 and hopefully later.
But it’s not urgent.

**Comment by palmskog** [comment]
OK, then I plan to do a PR review and do a pass over CI in the next day or so.

**Review by palmskog — APPROVED** [review]
Looks good to me now, I did some small adjustments to opam packages and CI to allow 8.18 and MathComp 1.18.0.

**Pull request merged**
